language: go
sudo: required
dist: trusty

go:
 - 1.9.2

addons:
   apt:
     packages:
       - libnetfilter-queue-dev
       - libnetfilter-log-dev
       - libnetfilter-conntrack-dev
       - libnetfilter-conntrack3
       - libnetfilter-conntrack3-dbg
       - iptables
       - ipset

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - sudo apt-get update
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install

install:
  - go get -t -v ./...

script:
  - gometalinter.v1 --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=structcheck --enable=aligncheck --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=varcheck --enable=interfacer --enable=goconst --enable=gosimple --enable=staticcheck --enable=unused --enable=misspell --deadline=5m -e mock ./...
  - sudo -E env "PATH=$PATH" go test ./...
