language: go
sudo: required
dist: trusty

go:
 - 1.8.1

addons:

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure -v
  - sudo apt-get install conntrack

script:
  - gometalinter.v1 --vendor  --disable-all  --enable=vet --enable=golint --enable=deadcode --enable=goimports --enable=goconst --enable=misspell  --deadline=5m -e mock./...
  - sudo -E env "PATH=$PATH" go test ./...
