language: go
sudo: required
dist: trusty

go:
 - 1.8.1

addons:

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure -v
  - sudo apt-get install conntrack

script:
  - gometalinter.v2 --vendor --skip=mockdocker --disable-all --enable=vet --enable=vetshadow --enable=errcheck --enable=golint --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=interfacer --enable=goconst --enable=misspell --deadline=10m ./...
  - sudo -E env "PATH=$PATH" go test ./...
